[build]
  publish = "build"
  command = "pip install -r requirements.txt && python build.py"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Language = ["zh"]}